config/routes.rb
Rails.application.routes.draw do
  get 'users/profile'
  devise_for :users
  get '/u/:id', to: 'users#profile', as: 'user'
  # /posts/1/comments/4
  resources :posts do 
    resources :comments
  end
  get 'about', to: 'pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "pages#home"
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true, length: {minimum: 5, maximum: 50}
    validates :title, presence: true, length: {minimum: 10, maximum: 1000}
    belongs_to :user
    has_many :comments, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, excert: %i[show index]
  # GET /posts or /posts.json
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post.update(views: @post.views + 1)
    @comments = @post.comments.order(created_at: :desc)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %> 
  <% if post.errors.any? %> 
    <div style="color: red"> 
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2> 
 
      <ul> 
        <% post.errors.each do |error| %> 
          <li><%= error.full_message %></li> 
        <% end %> 
      </ul> 
    </div> 
  <% end %> 
 
  <div> 
    <%= form.label :title, style: "display: block" %> 
    <%= form.text_field :title ,class: "form-control"%> 
  </div> 
 
  <div> 
    <%= form.label :body, style: "display: block" %> 
    <%= form.text_area :body,class: "form-control" %> 
  </div> 
 
  <div> 
    <%= form.submit %> 
  </div> 
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
    <h2><%= post.title %><h2>
    <h4> posted by <%= link_to post.user.name, user_path(post.user) %></h4>
    <h6><%= pluralize(post.views, "view") %><h6>
    <div>
    <%= post.body %>
    </div>
</div>

app/views/posts/edit.html.erb
<div class="container2">

    <div class="row2">
      <div class="box2">

<h1>Editing post</h1>
<div class ="form-contro">
<%= render "form", post: @post, class: "form-control" %>
</div>
<br>
<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>
</div>

app/views/posts/index.html.erb
<body class=post>
           <%= link_to "New post", new_post_path, class: "btn btn-primary"%>

<div class="container4">
  <h1 class="h1">Posts</h1>
  <div id="posts">
    <% @posts.each do |post| %>
      <div class="contabolasi">
        <%= render post %>
      <p>
        <%= link_to "Show this post", post, class: "btn2" %>
      </p>
      </div>
    <% end %>
 
  </div>

  </div>
  </body>

app/views/posts/new.html.erb
<div class="container2">
<img class="img_2"src="https://logodix.com/logo/1680519.jpg" alt="">
    <div class="row2">
      <div class="box2">


<div class="container5">
<h1 >New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts",  posts_path  %>
</div>
</div>
</div>
</div>
    </div>
</div>

app/views/posts/show.html.erb
<div class="container10">
<div class ="but">

<div class="box11">

<div class=row11>
  <%= render @post %> 
 </div>
  </div>
  <div class ="but1">
<% if @post.user == current_user %> 
     
    <%= link_to "Edit this post", edit_post_path(@post), class: "btn btn-primary" %>
    <%= link_to "Back posts", posts_path, class: "btn btn-danger"%> 
    <%= button_to "Destroy this post", @post, method: :delete, class: "btn btn-success" %> 
    <% else %> 
    <%= link_to "Back to posts", posts_path %> 
  <% end %> 
  </div>
 </div>
<div class="box10">



 
 
<div class="container11">
  <%= render 'comments/form',  
    post: @post,  
    comment: @post.comments.build, 
    submit_label: "Reply" %> 
  <% @comments.each do |comment| %> 
    <%= render 'comments/comment',  
    post: @post,  
    comment: comment %> 
  <% end %> 
 
</div>
 
  
</div>

</div>


 
 